### PR TITLE
style: formatted with `black eegnb/`

### PR DESCRIPTION
**Pull request by ErikBjare**
Used the wonderful [black](https://github.com/psf/black) to format the codebase.

Kind of a "meaningless" change (there are benefits to consistent formatting, but I won't argue them here), just wanted to put the suggestion out there.

Can wait for consideration until *after* all the upcoming hackathon PRs are merged (reapplying is trivial).

Someone will inevitably mention that this breaks `git blame` et al, but you can use `git blame --ignore-rev=<commit>` (or `--ignore-rev-file=<filename-with-commit-ids.txt>`) to have it ignore the style applying commits.

**Edit:** I've reconsidered running with `--skip-string-normalization` since the black docs explicltly recommended against it. Better doing things properly and once. 

For reference, here are counts of `'` vs `"`:

```
$ git grep -hoI "'" eegnb/ | wc --words
1562
$ git grep -hoI '"' eegnb/ | wc --words
646
```

### CODE REVIEW

**Comment by ErikBjare** [comment]
CI is failing because of this needed fix: #31

**Comment by JohnGriffiths** [comment]
Sounds like a good idea to me.

**Comment by hubertjb** [comment]
I think using something like black is a good idea overall. We decided against it in braindecode (see https://github.com/braindecode/braindecode/pull/32) to instead use flake8 and rely on the CI to catch formatting problems. But if we don't care whether the code is pep8 compliant then using black is probably a good way to save time! :)

**Comment by JohnGriffiths** [comment]
ok, approving if no objections ?

**Comment by ErikBjare** [comment]
@JohnGriffiths Merge #41 when ready and then I'll reapply the formatting and merge.

**Pull request merged**
