### PR TITLE
automatically cue signal quality check when running experiments

### LINKED ISSUE #135: Add option for signal quality checker when running experiments
When running experiments, users should be able to verify the quality of their signal right before starting an experiment.

### PR DESCRIPTION
**Pull request by JohnGriffiths**
Added functionality to automatically initiate signal quality check when running experiments. 

The `check_report` command line program is executed immediately before the `run_experiment` command. When the interactive experiment prompt selection is called by `eegnb runexp -ip`, the signal quality check prompt appears immediately after the initial experiment and device selections, and immediately before the start of the experiment. 

In the process of doing this, this PR also includes a bit of rationalization of functions from the `introprompt.py` and `__main__.py` functions in the `cli` folder. Specifically, the EEG device object creation is (as default behaviour) moved out of the intro prompt command and intro the main function. This was necessary here because the EEG object also needs to be created for the signal quality check, so the reorganization avoids those commands being called twice in two separate places. 

Checked for muse. Seems to be working ok. Also needs testing for Neurosity and OpenBCI. 

Perhaps could be some small improvements in the command line messages.

### CODE REVIEW

**Comment by JohnGriffiths** [comment]
@oreHGA  - I think the edit was correct, but CI still failing and I'm a bit baffled by the current error.

**Comment by oreHGA** [comment]
Hey @JohnGriffiths - they look to be more typing errors... taking another stab at resolving them now

**Comment by oreHGA** [comment]
@JohnGriffiths  Added some changes to this and we should be good to go if build succeeds (fingers crossed lol)
- removed the dictionary usage and went back to using the eegdevice class... we don't need to create it multiple times since we can pass the object across
- updated the underlying sigqual method to use upper threshold (of 15) and lower threshold of (1) - <1 assumes no contact
- added prompt to the user to optionally cancel signal quality checks after 5 tries  (we show them a summary first so they have a signal of how valuable recordings will be)
- minor type checking fixes

Tested on Neurosity and works fine too
image

image

image

**Review by oreHGA — APPROVED** [review]

**Review by ErikBjare — APPROVED** [review]
LGTM, nice work!

**Comment by ErikBjare** [comment]
I have no idea why the Ubuntu 18.04 CI segfaults on `eegnb --help`. Seems to only be an older Ubuntu thing, so maybe fine/spurious?

I say merge anyway.

**Comment by devyansh** [comment]
Hello, I tested out the OpenBCI Cyton with this updated PR to test the signal quality and I am getting some errors after selecting 'y' on the signal quality prompt. Here are the screenshots:


Capture

Capture2



Capture3

**Comment by oreHGA** [comment]
Thanks for reporting @devyansh .. I think what's happening here is that brainflow stream did not have up to `n_samples`  (in this case 256) in the stream when we do the [assertion check](https://github.com/NeuroTechX/eeg-notebooks/blob/d482da54d7461ee1a165c0f22a8cc39c57d065c5/eegnb/analysis/utils.py#L386)

I just added an update to wait for like 10seconds for openbci devices. Can you pull the latest changes on this branch & retry?

**Comment by JohnGriffiths** [comment]
Added fix to run checker with 10 repeats by default not 5. 

With this, I am able to run the signal quality checker with openbci ok. 

There's an issue with how we treat the std values however. 

I don't fully understand this yet but here are some things I have observed:


1. Ultracortex sitting on desk. 

```
Signal quality:
   Fp1: x  (std:   0.4)
   Fp2: x  (std:   0.4)
    C3: x  (std:   0.5)
    C4: x  (std:   0.5)
    P7: x  (std:   0.9)
    P8: √  (std:   5.5)
    O1: √  (std:   6.6)
    O2: √  (std:   5.7)
Bad channels: Fp1, Fp2, C3, C4, P7
```

```
Signal quality:
   Fp1: x  (std:   0.0)
   Fp2: x  (std:   0.1)
    C3: x  (std:   0.4)
    C4: x  (std:   0.2)
    P7: √  (std:   1.8)
    P8: √  (std:   5.6)
    O1: √  (std:   6.7)
    O2: √  (std:   5.8)
Bad channels: Fp1, Fp2, C3, C4
```

2. Ultracortex sitting on desk, bias and reference ear clips on ears.

```
Signal quality:
   Fp1: √  (std:  12.4)
   Fp2: √  (std:  12.4)
    C3: √  (std:  12.4)
    C4: √  (std:  12.4)
    P7: √  (std:  12.4)
    P8: √  (std:  12.4)
    O1: √  (std:  12.4)
    O2: √  (std:  12.4)
No bad channels
```

```
Signal quality:
   Fp1: √  (std:  12.4)
   Fp2: √  (std:  12.4)
    C3: √  (std:  12.4)
    C4: √  (std:  12.4)
    P7: √  (std:  12.4)
    P8: √  (std:  12.4)
    O1: √  (std:  12.4)
    O2: √  (std:  12.4)
No bad channels
```


3. Ultracortex on head, bias and reference ear clips not on ears


```
Signal quality:
   Fp1: √  (std:   6.0)
   Fp2: √  (std:   5.0)
    C3: √  (std:   9.8)
    C4: √  (std:  10.0)
    P7: √  (std:  10.0)
    P8: √  (std:  10.0)
    O1: √  (std:  10.0)
    O2: √  (std:  10.0)
No bad channels
```


```
Signal quality:
   Fp1: √  (std:   6.9)
   Fp2: √  (std:   5.9)
    C3: √  (std:  10.1)
    C4: √  (std:  10.0)
    P7: √  (std:  10.1)
    P8: √  (std:  10.1)
    O1: √  (std:  10.1)
    O2: √  (std:  10.1)
No bad channels
```



4. Ultracortex on head, bias and reference ear clips on ears

```
Signal quality:
   Fp1: √  (std:   1.0)
   Fp2: √  (std:   4.5)
    C3: √  (std:   1.8)
    C4: √  (std:   2.4)
    P7: √  (std:   1.7)
    P8: √  (std:   1.5)
    O1: √  (std:   1.5)
    O2: √  (std:   3.3)
No bad channels
```

```
Signal quality:
   Fp1: √  (std:   1.1)
   Fp2: √  (std:   2.8)
    C3: √  (std:   1.5)
    C4: √  (std:   2.2)
    P7: √  (std:   2.9)
    P8: √  (std:   2.9)
    O1: √  (std:   3.3)
    O2: √  (std:   3.9)
No bad channels
```


5. Ultracortex on head, bias and reference ear clips on ears, FP2 electrode unscrewed from frame and hanging free

```
Signal quality:
   Fp1: √  (std:   1.0)
   Fp2: √  (std:  12.4)
    C3: √  (std:   4.0)
    C4: √  (std:   4.7)
    P7: √  (std:   4.9)
    P8: √  (std:   4.9)
    O1: √  (std:   4.8)
    O2: √  (std:   6.0)
No bad channels
```


```
Signal quality:
   Fp1: x  (std:   0.9)
   Fp2: √  (std:  12.4)
    C3: √  (std:   3.9)
    C4: √  (std:   4.6)
    P7: √  (std:   4.7)
    P8: √  (std:   4.8)
    O1: √  (std:   4.6)
    O2: √  (std:   5.9)
Bad channels: Fp1
```



Current thinking, therefore: 

- We will need device-specific threshold criteria
- For OpenBCI we will need to assume that device is on head and reference electrodes attached; but stds won't give us clear indication of this
- std threshold maybe should be an upper bound of 6-9?
  


@devyansh @oreHGA @JadinTredup @retiutut @ErikBjare any thoughts?

**Comment by oreHGA** [comment]
Thanks for testing with OpenBCI @JohnGriffiths ! Glad to know things their devices are covered too. We're very close to merging this 🚀

```
We will need device-specific threshold criteria
For OpenBCI we will need to assume that device is on head and reference electrodes attached; but stds won't give us clear indication of this
std threshold maybe should be an upper bound of 6-9?
```

I agree that we will need to set std values per device.

- The options I set were based on my conversation with Alex C. from Neurosity (https://github.com/NeuroTechX/eeg-notebooks/blob/fc9d260707dca7685f4460a6a056c852b412b80b/eegnb/analysis/utils.py#L417) 
- I think we can start with range of 6-9 for openbci  (@jartuso is this something you can validate as the average values are for openbci devices?)
- @ErikBjare do you have the average std values handy for muse devices?
- is there any other "supported" device class for ntcs missing?

**Comment by JohnGriffiths** [comment]
@ErikBjare tell me what you think. I've run `eegnb checksigqual` and `eegnb runexp` many times on this PR now with muse and openbci. For both the muse2016 and museS I have it's been irritatingly long to get all stds under 15. So I think I want to recommend 20. That is certainly on the high side though. 

Should be aware that if we set high stds then people won't have the opportunity to try to get them lower if they want to as it will move on automatically after 2 successful runs. 

But even so I'm inclined to lean towards not pissing people off too much. 

Thoughts?

**Comment by JohnGriffiths** [comment]
@oreHGA - thanks for getting the device specific options code down.

some small edits here. working ok for me now.

LMK if you think looks good and let's get this one merged.

**Comment by oreHGA** [comment]
Looks good to me! Tested & it works. Will let you do the honors :)

**Pull request merged**
