### PR TITLE
enhancements to signal quality check function

### LINKED ISSUE #97: Add signal quality checks before recording starts
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

This will be based off @ErikBjare 's take on the problem - https://erik.bjareholt.com/thesis/Signal.html

- We will add a new flag to command line to check signal quality : eegnb runexp [flag for quality check]

Results will be placed on the command line prompt with a suggestion on changes to make to improve quality.

_What is the scenario this would be used?_

Before the recording gets started, the quality check happens to make the user aware of how valuable their recordings will be for analysis moving forward.

Initially targeting muse devices, but we aim to generalize to different device types.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by JohnGriffiths**
Fixed some minor issues and added enhancements to @ErikBjare 's implementation. 

1. Moved core function to `devices.EEG.check_report`. 

```python
def check_report(self, n_times: int=10, pause_time=5, sample_rate=256, thres_var=100,n_goods=2):
```

Makes more sense than `cli.__main__`, and facilitates python api usage option. Replaced the cli code with a minimal wrapper. 

2.  Replaced checkmarks with sqrt signs

Checkmarks weren't rendering in windows miniconda terminal for me. 
The sqrt signs look pretty close to checkmarks, fortunately. 

3. Add `n_goods` parameter

This was response to a comment in the code, sth like 'TO DO: allow multiple checks'

Keeps a counter for number of good checks, and break out of the loop (confirming good signal quality) after `n_goods` back-toback good checks. Set default to 2. Previous behaviour would be recovered by `n_goods=1`.  

4. Parameterized `sample_rate` variable

Pause time is used together with sample rate to define number of samples to use in the window

```python
res, var = self.check(n_samples=pause_time * sample_rate)
```

Values other than 256 for this probably only relevant to non-muse devices, when those implementations are done. 

5. Various additional info given in command line output

Usage 1: Python API
----------------------

```python
from eegnb.devices.eeg import EEG
eeg = EEG(device='museS')
eeg.check_report(n_goods=3, thres_var=80, pause_time=10))
```

```python
from eegnb.devices.eeg import EEG
EEG(device='museS').check_report()
```

Usage 2: CLI
-----------------

```bash
eegnb checkreport --eegdevice museS
```

(note: tried to implement flags for parameters here, but kept defaulting to `None` and erroring, so removed. Should be possible to add those flags back to extend command line usage options)

Notes:
-------

- Brainflow implementation needed next!  ( @oreHGA ;)  )

- I have noticed that the variance values seem much higher than the `muselsl` viewer. Are they calculating a different number? Would be good to align fully with that implementation if not.

### CODE REVIEW

**Review by oreHGA — APPROVED** [review]
Looks good to me!

**Review by ErikBjare — COMMENTED** [review]
Sorry for being AWOL, will hopefully find time to join the meeting tomorrow.

Looks fine, but I don't agree with moving the function to the EEG class. 

I can understand the desire to make it available as part of the public API outside the CLI, but in the interest of keeping the `EEG` class lean and to the point, I don't think the EEG class should have specific higher-level functions with terminal output like this directly. 

Better to keep it as a separate function which takes an `eeg` instance as an argument, imo. Should be pretty easy to just move it out.

> I have noticed that the variance values seem much higher than the muselsl viewer. Are they calculating a different number? Would be good to align fully with that implementation if not.

I think the difference is that the muselsl viewer uses the std instead of the var.

**Edit:** Yup, my original code uses `np.std` too, this indeed uses `np.var`.

**Comment by JohnGriffiths** [comment]
> I can understand the desire to make it available as part of the public API outside the CLI, but in the interest of keeping the EEG class lean and to the point, I don't think the EEG class should have specific higher-level functions with terminal output like this directly.

Ok. So, move to `eegnb.analysis.utils` then?

No meeting tomorrow FYI. Next week is the next one.

**Comment by oreHGA** [comment]
> I think the difference is that the muselsl viewer uses the std instead of the var.
Edit: Yup, my original code uses np.std too, this indeed uses np.var.

@ErikBjare Could this why I'm getting very high values when testing with the notion device?

Wondering if the threshold should change per device type? Or there's something else ( see PR #114 )

**Comment by ErikBjare** [comment]
@JohnGriffiths Gotcha, moving to `eegnb.analysis.utils` sounds good!

@oreHGA Commented on your PR, looks to be a scaling issue.

**Comment by JohnGriffiths** [comment]
> Yup, my original code uses np.std too, this indeed uses np.var

Ok let's switch to `np.std`

**Comment by JohnGriffiths** [comment]
@ErikBjare  @oreHGA  - updates:

1. Moved the `check` functions to `analysis.utils` as suggestions by @ErikBjare 

2. Changed the sig qual metric from `np.var` to `np.std`. Thresholds adjusted accordingly. This should now be consistent with the muselsl signal viewer. 


If no objections, I would like to go ahead and merge this, so that it is available for people testing the NTCS instructions. 

Further future work to do on this functionality:

- Add usage description to documentation (@AyrusCode @HVjay  - please take this one)
- Figure out the neurosity/brainflow units strangeness
- Decide + implement device-specific variants of e.g. the std threshold etc.

**Review by oreHGA — APPROVED** [review]
Awesome! Looks good to merge.

**Pull request merged**
