### PR TITLE
Adds brainflow support to signal quality check

### LINKED ISSUE #97: Add signal quality checks before recording starts
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

This will be based off @ErikBjare 's take on the problem - https://erik.bjareholt.com/thesis/Signal.html

- We will add a new flag to command line to check signal quality : eegnb runexp [flag for quality check]

Results will be placed on the command line prompt with a suggestion on changes to make to improve quality.

_What is the scenario this would be used?_

Before the recording gets started, the quality check happens to make the user aware of how valuable their recordings will be for analysis moving forward.

Initially targeting muse devices, but we aim to generalize to different device types.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by oreHGA**
Based on #113, this initializes a brainflow stream and passes data to the signal quality check methods.

These changes seem to work fine when testing on my notion 2. Little caveat,

I couldn't get the any of my recording samples to be marked as "good" (my hair? the function? how the data is being passed? not sure - but I tried to make sure electrodes were touching my scalp). 

image

The neurosity console did some some channels as green though when I ran them side by side. Not sure how they're measuring quality but it'll be great if we can get tests in from multiple people/devices.

```
eegnb checkreport -ed notion2
```

### CODE REVIEW

**Comment by ErikBjare** [comment]
The values look off by roughly 1000x (and the `var`, consequently, by ~1,000,000x), perhaps the values returned by brainflow are not in uV? Does it behave reasonably if you scale everything by 1/1000?

Edit: According to [the docs](https://brainflow.readthedocs.io/en/stable/DataFormatDesc.html) the unit should be uV, I wonder why it seems to not be the case?

**Comment by JohnGriffiths** [comment]
@oreHGA @JadinTredup @ErikBjare - fyi I can fix the above merge conflicts, but don't have a brainflow device to easily test this with currently.

**Comment by JohnGriffiths** [comment]
@oreHGA - I starting going through the merge conflicts. The conflicts per se look resolvable, but a larger issue is that the location of the `check...` functions has moved from `devices/eeg.py` to `analysis/utils.py` since the present branch was checked off master. 

The combination of additions and removals **does not look easily solvable by rebasing.** 

So, I am **copying your changes to the appropriate files in a new branch and PR**; will link below shortly. 
( update: [here](https://github.com/NeuroTechX/eeg-notebooks/pull/124) )

And then if all is well, **will merge that PR and close the present PR without merging.** 

LMK if any issues with this approach.

**Comment by oreHGA** [comment]
Sounds good to me. Thanks for picking this up @JohnGriffiths ! I'll test things out with your branch now

**Comment by oreHGA** [comment]
Abandoning in favor or #124

**Pull request closed without merging**
