### PR TITLE
ci: fix broken CI

### PR DESCRIPTION
**Pull request by ErikBjare**
@JohnGriffiths please be more careful next time, heh: https://github.com/NeuroTechX/eeg-notebooks/commit/3efcb158f5cb2111072320a67046315789c3101b

## TODO

 - [ ] Update instructions
 - [ ] ...?

## Changes

 - Updated psychopy
 - Updated minimum Python to 3.8
   - Required because psychopy now depends on tobii-research (another psychopy dep we wont use, sigh...) which is Python>=3.8
 - Updated seaborn to latest
   - Replaced use of removed `tsplot` with custom function
 - Fixed some examples

### CODE REVIEW

**Comment by ErikBjare** [comment]
And @JohnGriffiths why is `psychtoolbox` even needed? Why is it not in the requirements file? What does the `JG_ADD` comment mean?

**Comment by ErikBjare** [comment]
Ah, I assume psychtoolbox was to fix https://discourse.psychopy.org/t/missing-sound-libraries-for-psychopy3-standalone-release-3-2-3-for-win32/9162

However, it was already installed, so it had no effect. Added pygame instead.

Edit: adding pygame also had no effect.

**Comment by ErikBjare** [comment]
I'd also like to note that the dependency hell that caused this would have been handled by poetry, were we to use it.

**Comment by ErikBjare** [comment]
Alright, so this PR got a bit messier than first thought. Looks like a bunch of issues arising from having a >2yr old version of psychopy... Hoping psychopy has decent backwards compatibility.

**Comment by ErikBjare** [comment]
Ugh, apparently psychopy now depends on tobii-research, which is only available for Python 3.8+

Python 3.7 is EOL in ~1 year anyway, might be time to bump it.

**Comment by ErikBjare** [comment]
Now only macOS is failing, needs something like https://github.com/bambocher/pocketsphinx-python/pull/71

**Comment by ErikBjare** [comment]
Fixed seaborn>=0.11 compatibility (which dropped tsplot).

Building docs is still failing, but I don't think that's related to the changes.

**Comment by ErikBjare** [comment]
@JohnGriffiths This PR should now be an overall major improvement, but still some minor stuff needed (fix building docs & building on macOS). That'll have to wait for another PR though.

There may still be bugs or more testing needed, esp with the updated versions of stuff, but it's not sustainable to stay on the old versions anyway (as that'll lead to its own problems) so better get this out of the way.

**Comment by ErikBjare** [comment]
Merging.

**Comment by JohnGriffiths** [comment]
Thanks for doing the work on this @ErikBjare . Timing is not great though as we have just launched NTCS this week with e-mail out to thousands of of openbci users and this merge has broken installation.

**Comment by JohnGriffiths** [comment]
Our [Installation instructions](https://github.com/NeuroTechX/eeg-notebooks/blob/master/doc/getting_started/installation.rst) currently say to use py37 and install wxpython.

```
conda create -n "eeg-notebooks" python=3.7 git pip wxpython
conda activate "eeg-notebooks"
git clone https://github.com/NeuroTechX/eeg-notebooks
cd eeg-notebooks
pip install -e .
```

I am troubleshooting this now but definitely just switching to `python=3.8` doesn't work as there's no `wxpython` for py37. 

Trying to recall now why we settled on that `wxpython` instruction (was definitely an interim fix). We did go round the houses between py37, py38, and py39 last time we tackled this and settled on 3.7.

**Comment by JohnGriffiths** [comment]
Also important = any installation instruction updates need to be reflected in the docs instructions, and currently we have a build failure in the docs, so can't actually change the documentation instructions. 

I have tried several times to resolve this problem but haven't been able to yet. The doc build seems to work fine on all local machines I've tried so a bit stumped.

**Comment by JohnGriffiths** [comment]
install with py38 is failing on two out of two windows machines for me now. have you tested this? are there extra install instructions? 

might need to revert this PR. 

@oreHGA @JadinTredup if you got a mo to check on this would be great as is pretty time critical.

**Comment by ErikBjare** [comment]
I'll jump on it

Sorry about the NTCS launch, did not see the announcement until later!

We can always create a revert commit and merge it back later.

**Comment by ErikBjare** [comment]
There are wxPython wheels for Python 3.8 here, as detailed in `requirements.txt`: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/

**Comment by ErikBjare** [comment]
@JohnGriffiths I have a revert for this ready to go, just give me the word!

**Comment by JohnGriffiths** [comment]
Yeah I think revert for now and we can work on the PR as a priority matter

**Pull request merged**
