### PR TITLE
Documentation changes

### LINKED ISSUE #117: Documentation tweaks for NTCS
Look for improvements / weak points in the documentation; propose changes

### PR DESCRIPTION
**Pull request by hvjay**
Small documentation changes to running experiments and streaming. Added instructions for CLI data zipper function.

### CODE REVIEW

**Comment by JohnGriffiths** [comment]
@ErikBjare @HVjay  - can you tell why the typecheck test is failing here?

**Comment by ErikBjare** [comment]
~~Probably just a stricter check in a newer version of mypy.~~ Nvm, looked like it just failed to install dependencies for some spurious reason, I re-ran the pipeline and it might pass fine.

I wouldn't worry about it and just go ahead and merge.

BTW I might not make it to the meeting today, but I'll try.

**Comment by JohnGriffiths** [comment]
Yeah it's a weird error for a freshly installed OS. 

Maybe the `update fix-missing` line will work?

**Comment by oreHGA** [comment]
I think, pulling from master should resolve this... I experienced a similar error and made changes in this PR #124

**Comment by hvjay** [comment]
@oreHGA pulled from master and checks works, should I merge?

**Comment by oreHGA** [comment]
Yep! Go for it 💯

**Pull request merged**
