### PR TITLE
add 'version 2' upated brainflow sigqual support functions

### LINKED ISSUE #97: Add signal quality checks before recording starts
## 📝 Provide a description of the new feature

_What is the expected behavior of the proposed feature?_

This will be based off @ErikBjare 's take on the problem - https://erik.bjareholt.com/thesis/Signal.html

- We will add a new flag to command line to check signal quality : eegnb runexp [flag for quality check]

Results will be placed on the command line prompt with a suggestion on changes to make to improve quality.

_What is the scenario this would be used?_

Before the recording gets started, the quality check happens to make the user aware of how valuable their recordings will be for analysis moving forward.

Initially targeting muse devices, but we aim to generalize to different device types.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by JohnGriffiths**
Moved @oreHGA 's brainflow support additions to `devices.eeg.py` and `analysis.utils.py`.

c.f. discussion thread here 

https://github.com/NeuroTechX/eeg-notebooks/pull/114

Still in need of further testing with brainflow and muse devices before merging.

### CODE REVIEW

**Comment by JohnGriffiths** [comment]
@oreHGA @JadinTredup @ErikBjare - fixed some outstanding bugs. Ready for you to give a spin with neurosity devices, and merge to master if all ok. 

Reminder, two things we want to know:

- any actual bugs?

- @JadinTredup do you see the same scaling issues that Ore noted [here]( https://github.com/NeuroTechX/eeg-notebooks/pull/114 )?

**Comment by oreHGA** [comment]
@JohnGriffiths  Made some edits to get runs working successfully. @JadinTredup you can give this a go again now

``` eegnb checksigqual -ed notion2 ```

Mine still gives fails the checks but the numbers look smaller than those in https://github.com/NeuroTechX/eeg-notebooks/pull/114#issue-683075180 - could it be because we switched from `variance` to `standard deviation`?
image

we need more testing from other brainflow devices but I think the code is good at this point

**Review by oreHGA — APPROVED** [review]

**Comment by oreHGA** [comment]
> Mine still gives fails the checks but the numbers look smaller than those in [#114 (comment)]
> we need more testing from other brainflow devices but I think the code is good at this point

@JohnGriffiths @ErikBjare @JadinTredup - I had a chat with Alex M (Curia) and they mentioned this is expected because of the presence of active amplifiers on neurosity devices.

- muse uses passive electrodes and it's signal voltage ranges from 0-1600 microvolts
- neurosity uses active amplifiers and signal can range from -40000 to 40000 microvolts

We'd need a separate logic for calculating sig qual for devices with active amplifiers & passive electrodes 


edit: not sure how entirely correct this is, I think we accounted for the concern here by only doing quality checks on short samples not the whole dataset... I think the difference between brainflow and muselsl recordings is that brainflow records in uV and we need to /100000 to get into volts for MNE

**Comment by oreHGA** [comment]
@JohnGriffiths brainflow checks work now using @ErikBjare's [suggestion](https://github.com/NeuroTechX/eeg-notebooks/pull/114#issuecomment-875732471) to divide by 1000!

From my understanding MNE (which we use for the `iir` filter) expects data to be in V and brainflow returns in uV .... this means we should have divided by 1,000,000. I tried that too but that makes the values so small and all standard deviations are < 0.1

Not really sure why 1000 was the magic number but i'll take it 😂
image

As a side note, we should consider adjusting the threshold ranges for standard deviation in future. These are some classifications I got from Alex C (Neurosity).

```
thresholds = {
  bad: 15,
  good: 10,
  great: 1.5 // Below 1.5 usually indicates not connected to anything
}
```

**Comment by JohnGriffiths** [comment]
Excellent. Good to merge I think. 

@oreHGA  - re: threshold ranges - currently our default threshold of a 'good' tick is 10. 

So that would be consistent with Alex's numbers that you listed above right?

**Comment by oreHGA** [comment]
yep 15 would be the max accepted standard deviation for a good recording. I've updated the code to use that

**Pull request merged**
