### PR TITLE
fix: support Python 3.8 (and 3.9 on Linux)

### LINKED ISSUE #29: PyWinhook building wheel error
On Win10 using Anaconda 4.8.4

```
conda create -n eeg-notebooks python=3.6 pip
conda activate eeg-notebooks
pip install -r requirements.txt

 Building wheel for pyWinhook (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Morgan Hough\.conda\envs\eeg-notebooks\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MORGAN~1\\AppData\\Local\\Temp\\pip-install-ntayfg3e\\pywinhook\\setup.py'"'"'; __file__='"'"'C:\\Users\\MORGAN~1\\AppData\\Local\\Temp\\pip-install-ntayfg3e\\pywinhook\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\MORGAN~1\AppData\Local\Temp\pip-wheel-yrqp9qeq'
       cwd: C:\Users\MORGAN~1\AppData\Local\Temp\pip-install-ntayfg3e\pywinhook\
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pyWinhook
  copying pyWinhook\aa hook.py -> build\lib.win-amd64-3.6\pyWinhook
  copying pyWinhook\doc.py -> build\lib.win-amd64-3.6\pyWinhook
  copying pyWinhook\example.py -> build\lib.win-amd64-3.6\pyWinhook
  copying pyWinhook\HookManager.py -> build\lib.win-amd64-3.6\pyWinhook
  copying pyWinhook\__init__.py -> build\lib.win-amd64-3.6\pyWinhook
  running build_ext
  building 'pyWinhook._cpyHook' extension
  swigging pyWinhook/cpyHook.i to pyWinhook/cpyHook_wrap.c
  swig.exe -python -o pyWinhook/cpyHook_wrap.c pyWinhook/cpyHook.i
  error: command 'swig.exe' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for pyWinhook
  Running setup.py clean for pyWinhook
```

Need to use conda to install swig as there is no PyPI compatible package 

```
conda install swig

    running build_ext
    building 'pyWinhook._cpyHook' extension
    swigging pyWinhook/cpyHook.i to pyWinhook/cpyHook_wrap.c
    C:\Users\Morgan Hough\.conda\envs\eeg-notebooks\Library\bin\swig.exe -python -o pyWinhook/cpyHook_wrap.c pyWinhook/cpyHook.i
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Morgan Hough\.conda\envs\eeg-notebooks\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MORGAN~1\\AppData\\Local\\Temp\\pip-install-cb193sym\\pywinhook\\setup.py'"'"'; __file__='"'"'C:\\Users\\MORGAN~1\\AppData\\Local\\Temp\\pip-install-cb193sym\\pywinhook\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MORGAN~1\AppData\Local\Temp\pip-record-hrg_h6jz\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Morgan Hough\.conda\envs\eeg-notebooks\Include\pyWinhook' Check the logs for full command output.
```

Now looking for the required Visual Studio build tools 

https://stackoverflow.com/questions/48541801/microsoft-visual-c-14-0-is-required-get-it-with-microsoft-visual-c-build-t

I assume this is because of the Python 3.6 requirement. Installing just the Desktop C++ build tools using Studio 17 solves the remaining issue building the wheel. 

Studio 19 is the current version and using a Python 3.7 requirement or forcing a PyWinhook==1.6.1 in the requirements.txt could be alternative workarounds.

### LINKED ISSUE #50: Support newer Python versions
There seems to be a lot of issues when installing on other Python versions than 3.7, since I have a pretty extensive history of battling issues like these I thought I might give it a shot (especially now that we have a CI pipeline).

Documenting known issues here:

 - [x] Installing pywinhook on Windows on Python 3.9 requires extra build deps (swig, VS C++ tools) due to no prebuilt wheels being available on PyPI
    - Fixed by referencing wheels built elsewhere in requirements.txt
 - [x] Build errors for numpy/pandas
    - It seems this is merely due to the versions in requirements.txt being old. Using newer versions works just fine. (another reason for #22)
 - [ ] tables 3.6.1 has no wheels available for Python 3.9 on platforms other than Linux (see: https://github.com/NeuroTechX/eeg-notebooks/actions/runs/400623523)

### PR DESCRIPTION
**Pull request by ErikBjare**
Depends on #31

Fixes #29, Fixes #50 

Based on a similar solution in: https://github.com/ActivityWatch/aw-watcher-afk/pull/44

### CODE REVIEW

**Comment by ErikBjare** [comment]
Looks like `requirements.txt` doesn't accept user-supplied wheels for dependencies with pypi entries.

Another reason to look into #22 I guess.

**Comment by ErikBjare** [comment]
Might just have been the fact that wheels for Python 3.6 weren't available, bumping CI Python version to check if that's the case.

**Comment by ErikBjare** [comment]
CI passed, ready to merge (after #31) :tada:

**Comment by JohnGriffiths** [comment]
Just want to check: do we think the user-supplied wheels is the best option here, or is the pywinhook issue largely solved by moving to python 3.7?

**Comment by ErikBjare** [comment]
@JohnGriffiths From a second look at https://pypi.org/project/pyWinhook/#files it seems like there exists pywinhook wheels on PyPI for Python 3.7 and 3.8 (news to me), but indeed not for 3.9. 

Since there are wheels available for 3.9 (here: https://www.lfd.uci.edu/~gohlke/pythonlibs/), we might want to change this PR to only supply prebuilt wheels for Python 3.9 (and maybe for 3.6 since that's not on PyPI either, but we'll probably want to drop 3.6 support soon anyway).

Edit: It should be added that I intend to resolve issues with newer Python versions, as I've laid out in #50

**Comment by ErikBjare** [comment]
Supports Python 3.9 on Linux now, but one remaining issue with tables 3.6.1 on macOS and Windows where wheels are missing and requires HDF5 headers to be available (see #50)

**Comment by ErikBjare** [comment]
Looks like pyriemann broke with the latest scikit-learn, submitted a fix: https://github.com/alexandrebarachant/pyRiemann/pull/93

**Comment by JohnGriffiths** [comment]
I'm OK with merging this. 

But shlukd we be e currently waiting for the pyriemann fix PRs to be accepted before doing so?

**Comment by ErikBjare** [comment]
If so, we'll need to lower the sklearn constraint again, and leave Python 3.9 support for another PR. 

I'd suggest we just wait for it to get merged (or if it takes too long, fork pyriemann ourselves and switch to using that).

**Pull request merged**
