### PR TITLE
[work in progress] - Prose for Cueing task documentation 

### LINKED ISSUE #9: cueing notebook prose updates
There's a set of sphinx-gallery examples for the four notebooks that you contributed

https://neurotechx.github.io/eeg-notebooks/experiments/cueing.html  

which are slightly modified, but largely unchanged from your original notebooks. 

What we could do with is a go-over of those four pages

https://neurotechx.github.io/eeg-notebooks/auto_examples/visual_cueing/01r__cueing_singlesub_analysis.html# 

https://neurotechx.github.io/eeg-notebooks/auto_examples/visual_cueing/02r__cueing_group_analysis.html 

https://neurotechx.github.io/eeg-notebooks/auto_examples/visual_cueing/03r__cueing_behaviour_analysis_winter2019.html

https://neurotechx.github.io/eeg-notebooks/auto_examples/visual_cueing/04r__cueing_group_analysis_winter2019.html

 
Specifically: I was wondering if someone from your team or yourself could spare maybe an hour or so going through those and get back to me with the following:

- Some additional explanatory text for the experiment(s) in general
- Explanatory text for each code block section 
- Explanatory text describing what the figures are showing
- A short concluding paragraph for each page
- Citations of relevant papers (yours and others) in the above additions highly encouraged

If you guys don't have bandwidth for this atm, no worries. I thought I would ask as you folks would be best placed to do this, and I have a lot of other tasks to do with the rest of the documentation. Trying to get better at delegating!

If you think you could give this a stab: 

You can send the above info however is most convenient. 

Pull request on the source code would be ok - although the relationship of sphinx-gallery python source code embedded .rst to the webpage html isn't super obvious, and you have to compile the website to see it. So you might prefer to e.g. just grab the jupyter notebooks from  each webpage (c.f. download link at the bottom), and email me updated versions, or even just text file/email. Whatever you prefer.

### PR DESCRIPTION
**Pull request by kylemath**
PR to update prose on cueing task for documentation

### CODE REVIEW

**Comment by kylemath** [comment]
hit issue https://github.com/NeuroTechX/eeg-notebooks/issues/7 figures not loading in build docs

**Comment by kylemath** [comment]
addresses issue https://github.com/NeuroTechX/eeg-notebooks/issues/9

**Comment by kylemath** [comment]
This was still in progress as indicated by the title

**Comment by JadinTredup** [comment]
Sorry my bad, still getting used to working with git beyond simple commit/pushes. Do you want me to go ahead and revert it?

**Comment by JadinTredup** [comment]
Just reverted it, sorry about that.

**Comment by kylemath** [comment]
no sweat once im done Ill request a review

**Pull request merged**
