### PR TITLE
visual p100 test

### PR DESCRIPTION
**Pull request by pellet**
- I just used some images instead of using drawing up the checkerboard and red dot with code.
- I had to update the PsychoPy version because 2020.2.3 was using an old version of PsychXR which only supported up to Python v3.6.

Let me know of any thing I need to change, like consolidating this experiment with the existing VEP code before it can be merged.
Thanks a lot for this great open source project.

### CODE REVIEW

**Comment by JohnGriffiths** [comment]
Hi Ben. 

This looks great! 

There's quite a lot of interesting pieces here. I was wondering if you would be able to join an eegnb developer's meeting to talk us through a bit? Our next one is 10am EST on Thurs 20th. 

A few thoughts so far:

- Do you have an example dataset that shows the intended P100 effect and can be fetched and used in the docs example script ?
-  The `01r_p100_viz.ipynb` needs to be a `.py` file, and the sphinx gallery docs will build it into a jupyter notebook, as per the other examples. 
- Good job on finding the `develop` branch and submitting the PR to there. FYI though we are on the cusp of merging a [major refactor](https://github.com/NeuroTechX/eeg-notebooks/pull/183) on the `develop` branch that simplifies substantially the experiment definition process. I think it would be best if we wait until that is done before merging this PR with some adjustments to meet the new conventions.

**Comment by pellet** [comment]
Hi John, thanks for the quick feedback.
Yeah sure I'll try to join the next meeting to give an overview of the changes, I find running through pull requests over a video call a nice way to get people across changes.
I'll take a look into dealing with points you've raised - I'll try getting across the experiment refactor and think how these changes will fit.

**Comment by tmorshed** [comment]
To fix the build issue, especially for the Docs build. As @oreHGA mentioned, seeems like adding `pip install attrdict` before the `wxpython` install line

**Comment by pellet** [comment]
This work will be added in a new PR after merging the vr support for the n170 experiment.

**Pull request closed without merging**
