### PR TITLE
build: moved to pyproject.toml/poetry

### PR DESCRIPTION
**Pull request by ErikBjare**
I have no idea how, but I managed to close the previous PR with a force push somehow (https://github.com/NeuroTechX/eeg-notebooks/pull/22)... So here we go again.

### CODE REVIEW

**Comment by JohnGriffiths** [comment]
Note 1: New poetry release will have formal notion of dependency groups, consider using this in eegnb for separating a) streaming, b) stim pres, c) analysis ? 

Note 2: Ore desperately wants to have this working for new Macs specifically. Use OS specific options here with that?

**Comment by ErikBjare** [comment]
I have a Macbook Air M2 to test on now too, so giving this another shot. Hoping it will also fix CI.

**Comment by ErikBjare** [comment]
Good news! Looks like wxPython finally pushed wheels to PyPI: https://pypi.org/project/wxPython/4.2.0/#files

**Comment by JohnGriffiths** [comment]
closing this as the pip/build scenario has moved on a bit. 

we can and maybe should revisit the `poetry` question again in the future however.

**Pull request closed without merging**
